migrate pgsql installation from rpm to container-based
theforeman/foreman-quadlet pull request #62
Opened 2024-11-27 08:06 UTC by archanaserver

2024-11-27 08:08 UTC, archanaserver commented
idk what is wrong with image, it is failing everytime reading manifest in `registry.access.redhat.io/rhel9/postgresql-16:latest`?

2024-11-27 08:13 UTC, archanaserver commented
also i do not like doing this way, should i go with creating a separate role for postgresql and do the containerization work there? would it be good? any thoughts?

2024-12-03 01:46 UTC, ehelms commented
> idk what is wrong with image, it is failing everytime reading manifest in `registry.access.redhat.io/rhel9/postgresql-16:latest`?

This is an official Red Hat image locked behind subscriptions, only `ubi` is available for wide usage but I think we've realized it does not come in flavors like the `rhel` images.

2024-12-03 01:47 UTC, ehelms commented
> also i do not like doing this way, should i go with creating a separate role for postgresql and do the containerization work there? would it be good? any thoughts?

100% -- give it a role like all the other services

2025-01-30 14:44 UTC, ehelms commented on roles/postgresql/defaults/main.yml
> +postgresql_image: docker.io/library/postgres:16
We should stick with 13 for now to match our nightly deployment.

2025-01-30 14:44 UTC, ehelms commented on roles/postgresql/defaults/main.yml
> +postgresql_image: docker.io/library/postgres:16
We should stick with 13 for now to match our nightly deployment.

2025-01-30 14:44 UTC, ehelms commented on roles/postgresql/defaults/main.yml
> +postgresql_databases:
I think we should define this at the playbook level, or a wrapper role rather than hardcoding this role to knowledge of foreman/candlepin/pulp.

2025-01-30 14:46 UTC, ehelms commented on roles/postgresql/tasks/main.yml
> +      - "config_file=/etc/postgresql/postgresql.conf"
I am surprised we have to specify this, as postgresql on EL should have sane defaults set.

2025-01-30 14:49 UTC, ehelms commented on roles/postgresql/defaults/main.yml
> +postgresql_image: docker.io/library/postgres:16
This image is debian based, which means we would mix-n-match base OS which I think we said we do not want to do. Give this a try -- https://quay.io/repository/sclorg/postgresql-13-c9s

2025-02-06 10:04 UTC, archanaserver commented on roles/postgresql/tasks/main.yml
> +      - "config_file=/etc/postgresql/postgresql.conf"
Yeah, now I changed the way I did before, made it so complex earlier which wasn't necessary do dropped it for now.

2025-02-06 10:35 UTC, archanaserver commented
@ehelms how can we re run the workflow?

2025-02-06 14:07 UTC, ehelms commented
With Candlepin, the thing to usually check is the `candlepin.log` file:

`vi /var/log/candlepin/candlepin.log`

And the output I see is:
```
2025-02-06 13:59:51,400 [thread=main] [=, org=, csid=] ERROR org.candlepin.database.DatabaseConnectionManager - Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

2025-02-11 09:44 UTC, evgeni commented on roles/postgresql/templates/init.sh.j2
> +psql -v ON_ERROR_STOP=1 --username "$POSTGRESQL_USER" <<-EOSQL
As debugged together, the user variable is unset, so the script fails, and once we fix that the db creation needs to happen after the user creation, so this patch makes it work:

```
diff --git a/roles/postgresql/templates/init.sh.j2 b/roles/postgresql/templates/init.sh.j2
index d4c464a..afb706d 100644
--- a/roles/postgresql/templates/init.sh.j2
+++ b/roles/postgresql/templates/init.sh.j2
@@ -2,16 +2,16 @@
 set -e
 
 
+{% for user in postgresql_users %}
+psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
+    CREATE USER {{ user.name }} WITH PASSWORD '{{ user.password }}';
+EOSQL
+{% endfor %}
+
 {% for db in postgresql_databases %}
-psql -v ON_ERROR_STOP=1 --username "$POSTGRESQL_USER" <<-EOSQL
+psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
     CREATE DATABASE {{ db.name }};
     ALTER DATABASE {{ db.name }} OWNER TO {{ db.owner }};
 EOSQL
 {% endfor %}
 
-{% for user in postgresql_users %}
-psql -v ON_ERROR_STOP=1 --username "$POSTGRESQL_USER" <<-EOSQL
-    CREATE USER {{ user.name }} WITH PASSWORD '{{ user.password }}';
-    GRANT ALL PRIVILEGES ON DATABASE {{ user.databases | first }} TO {{ user.name }};
-EOSQL
-{% endfor %}
```

2025-02-11 17:58 UTC, ekohl commented on roles/postgresql/templates/init.sh.j2
> +    ALTER DATABASE {{ db.name }} OWNER TO {{ db.owner }};
Per https://www.postgresql.org/docs/current/sql-createdatabase.html you can set the owner on creation
```suggestion
    CREATE DATABASE {{ db.name }} OWNER {{ db.owner }};
```

2025-02-11 17:58 UTC, ekohl commented on roles/postgresql/templates/init.sh.j2
> +{% endfor %}
I was debating using [createuser](https://www.postgresql.org/docs/current/app-createuser.html) but reading the documentation I wonder how to properly deal with passing in the password.

Then my other thought was whether if it's better to create the users in a single query:
```suggestion
psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
{% for user in postgresql_users %}
    CREATE USER {{ user.name }} WITH PASSWORD '{{ user.password }}';
{% endfor %}
EOSQL
```

And if you take that latter step to the extreme: should there just be a single script that creates the users and the databases.

2025-02-11 17:58 UTC, ekohl commented on roles/postgresql/templates/postgresql.container.j2
> +Environment=POSTGRESQL_ADMIN_PASSWORD={{ postgresql_admin_password }}
These files will be world readable, meaning any user on the system can read the admin password. This should be supplied via a secret.

Having said that: why do we need an admin password? https://github.com/sclorg/postgresql-container/tree/master/13#postgresql-admin-account says you can still use local connections. Or is that insecure because we use the host network?

2025-02-11 17:58 UTC, ekohl commented on roles/postgresql/templates/init.sh.j2
By using `init` you don't guarantee the password is correct. Perhaps not relevant now, but for the long term: do we need to provide a mechanism to rotate passwords?

Another thing I'm worried about: this will contain plain text passwords in the container. Will that be a security risk?

By the default the container already contains code to create a single user (`POSTGRESQL_USER`, ` POSTGRESQL_PASSWORD`, `POSTGRESQL_DATABASE`) which could be provided via secrets. It makes me wonder what would be a good pattern. Should we have a PostgreSQL container for every database?

2025-02-19 20:22 UTC, archanaserver commented on roles/postgresql/templates/postgresql.container.j2
> +Environment=POSTGRESQL_ADMIN_PASSWORD={{ postgresql_admin_password }}
> These files will be world readable, meaning any user on the system can read the admin password. This should be supplied via a secret.

That's right! To address this i've moved the password storage to a dedicated secrets file and restrict file permission to `0600` so only container process can now access it. But I'm trying to do this with Podman secrets.

> 
> Having said that: why do we need an admin password? https://github.com/sclorg/postgresql-container/tree/master/13#postgresql-admin-account says you can still use local connections. Or is that insecure because we use the host network?

While the container allows local connections without a password here by default, but host networking exposes PostgreSQL to all network interfaces I believe(not just localhost). So without a password, anyone on the network could access the database with postgres privileges. And admin password is that is gonna adds a layer of security here, even if local connections are allowed. If we switch to a non-host network later, maybe the password isn't needed, but for now, it's safer.

2025-02-19 20:23 UTC, archanaserver commented on roles/postgresql/templates/init.sh.j2
> By using `init` you don't guarantee the password is correct. Perhaps not relevant now, but for the long term: do we need to provide a mechanism to rotate passwords?
>
It only works for initial step for now and isn't idempotent. I suppose we can add separate tasks to manage users/passwords or maybe we have Ansible modules to handle this, not sure. For now, yes we need that.
https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_user_module.html

> Another thing I'm worried about: this will contain plain text passwords in the container. Will that be a security risk?
> 
After looking at it that's valid point. Here the init script run once during container initialization, but the file is in `postgresql-init/` could expose secrets. So I restricted now dir permission to owner access but better would be do it with Podman secrets or file based, so that's another to-do.

> By the default the container already contains code to create a single user (`POSTGRESQL_USER`, ` POSTGRESQL_PASSWORD`, `POSTGRESQL_DATABASE`) which could be provided via secrets. It makes me wonder what would be a good pattern. Should we have a PostgreSQL container for every database?

Can't think of much but If we want strict isolation then we should adopt multiple containers, each with its own secrets and we gonna definitely need a private podman network in that case. Or I guess starting with a single container would be good but with a private network so we can revisit it later for multi-container isolation?

2025-03-04 14:35 UTC, ekohl requested changes

2025-03-04 14:35 UTC, ekohl commented on roles/postgresql/templates/postgresql.container.j2
> +PodmanArgs=--security-opt label=disable
Why is this needed?

2025-03-04 14:35 UTC, ekohl commented on roles/postgresql/tasks/main.yml
> +    dest: "/var/lib/pgsql/data/pg_hba.conf"
```suggestion
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
```

2025-03-04 14:35 UTC, ekohl commented on roles/postgresql/tasks/main.yml
> +- name: Deploy Quadlet configuration
In other places we use `containers.podman.podman_container` so why the direct implementation this time?

2025-03-04 14:35 UTC, ekohl commented on roles/postgresql/templates/postgresql.container.j2
> +Volume={{ playbook_dir }}/postgresql-init:/opt/app-root/src/postgresql-init:Z
I'm not a fan of mounting something from the playbook directory. In general I'd assume you can delete the "installer" and this would break that assumption. We've already made that mistake in the past (looking at `/root/ssl-build`) and I'd prefer to avoid it.

2025-03-04 14:35 UTC, ekohl commented on roles/postgresql/templates/postgresql.container.j2
> +EnvironmentFile=/etc/secrets/postgresql_admin_password
I'd prefer a podman secret that you expose via an environment variable. The `/etc/secrets` directory is non-standard and I'd like to avoid creating those.

2025-03-04 14:36 UTC, ekohl commented on playbooks/deploy.yaml
> +        databases: [candlepin]
This `databases` entry doesn't appear to be used.
```suggestion
```

2025-03-11 14:30 UTC, ekohl commented on roles/postgresql/tasks/main.yml
> +    timeout: 300
Taking lessons from https://github.com/theforeman/foreman-quadlet/pull/114, I'd really prefer if you used `sdnotify: true` on the PostgreSQL container definition so that it uses the built in notify support when the service is ready.

That way after a reboot you are also certain that anything that needs PostgreSQL can actually talk to PostgreSQL.

2025-03-14 13:47 UTC, evgeni commented on roles/postgresql/tasks/main.yml
> +    timeout: 300
`sdnotify: true` doesn't seem to work with the postgres container, but you can do
```
healthcheck: pg_isready
sdnotify: healthy
```

2025-03-18 07:55 UTC, evgeni commented on roles/postgresql/tasks/main.yml
> +  when: postgresql_users | length > 0
You can omit the `when` here, if the array is empty, the loop will not be executed :)

2025-03-18 07:55 UTC, evgeni commented on roles/postgresql/tasks/main.yml
> +  when: postgresql_databases | length > 0
You can omit the `when` here, if the array is empty, the loop will not be executed :)

2025-03-18 07:56 UTC, evgeni commented on roles/postgresql/tasks/main.yml
> +- name: Create PostgreSQL users
For this, the DB must be running already, so this (and the db creation) needs to happen after "Start the PostgreSQL Service"

2025-03-18 07:57 UTC, evgeni commented on roles/postgresql/tasks/main.yml
> +    mode: "0644"
If I am reading https://github.com/sclorg/postgresql-container/blob/master/13/root/usr/share/container-scripts/postgresql/common.sh#L228-L240 correctly, we don't need to configure hba in the container case, as the container is already configured as "everyone can connect"

2025-03-18 09:27 UTC, evgeni commented on tests/postgresql_test.py
> +    assert re.search(r"host\s+all\s+all\s+127\.0\.0\.1/32\s+md5", result.stdout)
You dropped the hba editing, so I think this test can be removed (and then the `re` import too)

2025-03-18 09:30 UTC, evgeni commented on roles/postgresql/tasks/main.yml
> +      POSTGRESQL_ADMIN_PASSWORD: "{{ postgresql_admin_password }}"
You created a secret for that above, so let's use it
```suggestion
    secrets:
      - 'postgresql_admin_password,target=POSTGRESQL_ADMIN_PASSWORD,type=env'
```

2025-03-18 09:31 UTC, archanaserver commented on tests/postgresql_test.py
> +    assert re.search(r"host\s+all\s+all\s+127\.0\.0\.1/32\s+md5", result.stdout)
Done!

2025-03-18 09:33 UTC, evgeni commented on roles/postgresql/defaults/main.yml
> +postgresql_hba_entries: []
This can be removed now (and so can the setting of it in `deploy.yaml`)

2025-03-18 09:57 UTC, evgeni commented on roles/postgresql/defaults/main.yml
> +postgresql_restart_policy: always
These two variables are unused right now. Do you have plans to use them?
(I don't think we *need* that flexibility right now, but it surely can be handy in the future)

2025-03-18 09:59 UTC, archanaserver commented on roles/postgresql/defaults/main.yml
> +postgresql_restart_policy: always
this was added with the earlier setup, but i guess we can drop it for now.

2025-03-18 10:52 UTC, ehelms commented
Great to see this working! How much data do we want on how upgrades work (https://github.com/theforeman/foreman-quadlet/issues/66) before we merge this change?

2025-03-18 11:53 UTC, evgeni commented
I would see those as separate problems (= no data required to merge this).

It seems the container does support running pg_upgrade if it starts with existing data and `POSTGRESQL_UPGRADE` variable was set:
- https://github.com/sclorg/postgresql-container/blob/e65d040374930106672d88a26b275ee02e56ab37/13/root/usr/bin/run-postgresql#L27
- https://github.com/sclorg/postgresql-container/blob/e65d040374930106672d88a26b275ee02e56ab37/13/root/usr/share/container-scripts/postgresql/common.sh#L408

So we might be rather lucky here and be able to orchestrate updates in a very similar way we do on base rhel

2025-03-18 15:09 UTC, ehelms commented
I'll do a final review of this PR then. @evgeni could you add those upgrade notes to https://github.com/theforeman/foreman-quadlet/issues/66 ?

2025-03-18 15:10 UTC, ehelms commented
@archanaserver Do you know if this container setup satisfies https://github.com/theforeman/foreman-quadlet/issues/106 ?

2025-03-19 08:53 UTC, archanaserver commented
> @archanaserver Do you know if this container setup satisfies #106 ?

No it doesn't, currently container setup by default uses `md5`. So I can take look into adding explici settings for `scram-sha-256`.

2025-03-19 12:00 UTC, ehelms approved these changes
The SCRAM update can be a follow up.

2025-03-19 12:00 UTC, merged